# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceType',
            fields=[
                ('surface_type_ref', models.AutoField(primary_key=True, serialize=False)),
                ('surface_type', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'SurfaceType',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_ref', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('number_of_rounds', models.IntegerField()),
                ('surface_type_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.SurfaceType')),
            ],
            options={
                'db_table': 'Tournament',
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayingCategory',
            fields=[
                ('tournament_pc_ref', models.AutoField(primary_key=True, serialize=False)),
                ('playing_category_ref', models.CharField(max_length=150)),
                ('tournament_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
            options={
                'db_table': 'TournamentPlayingCategory',
                'verbose_name_plural': 'Tournament Playing Category',
            },
        ),
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('tournament_type_ref', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_type', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TournamentType',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.TournamentType'),
        ),
    ]
