# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('entity_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('address_line', models.CharField(max_length=250)),
                ('address_line2', models.CharField(max_length=250)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('address_ref', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_name', models.CharField(max_length=200)),
                ('country_code', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Specified')], default='N', max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateTimeField(auto_now=True, verbose_name='Date of Birth')),
                ('player_ref', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Country')),
            ],
            options={
                'db_table': 'Player',
            },
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('player_ref', models.AutoField(primary_key=True, serialize=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
            options={
                'db_table': 'PlayerRegistration',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='player_ref',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
